export const textContent = {
  en: {
    greeting: "Hi there! 👋",
    subtitle1_1: "Check out the ",
    subtitle1_2: " statistics to analyze its marketvalue within a given date range.",
    subtitle2: "Start by defining a range you want to inspect from below.",
    input1: "Select the beginning date of the range",
    input2: "Select the ending date of the range",
    submit: "Continue",
    placeholder: "DD / MM / YYYY",
    back: "Go back",
    bearish: "Longest bearish trend",
    volume: "Highest trading volume",
    profit: "Most profitable range",
    from: "from",
    to: "to",
    days: "days",
    in: "in",
    profitTip: "In order to achieve the greatest possible revenue within date range, you should have:",
    buy: "bought in",
    sell: "sell in",
    revenue: "Then the revenue would have been"
  },
  fi: {
    greeting: "Heippa! 👋",
    subtitle1_1: "Tarkastele ",
    subtitle1_2: "-tilastoja analysoidaksesi sen markkina-arvoa tietyllä aikavälillä.",
    subtitle2: "Aloita määrittelemällä alta aikaväli, jota haluat tutkia.",
    input1: "Valitse tutkittavan aikavälin aloituspäivämäärä",
    input2: "Valitse tutkittavan aikavälin lopetuspäivämäärä",
    submit: "Tarkastele",
    placeholder: "PV / KK / VVVV",
    back: "Takaisin",
    bearish: "Pisin laskeva trendi",
    volume: "Korkein kauppojen määrä",
    profit: "Tuottoisin aikaväli",
    from: "alkaen",
    to: "päättyen",
    days: "päivää",
    in: "päivämääränä",
    profitTip: "Parhaan mahdollisen tuoton saamiseksi annetulla aikavälillä, sinun olisi tullut:",
    buy: "ostaa",
    sell: "myydä",
    revenue: "Tällöin tuotto olisi ollut"
  }
}