export const textContent = {
  en: {
    greeting: "Hi there! 👋",
    subtitle1_1: "Check out the ",
    subtitle1_2: " statistics to analyze its marketvalue within a given date range.",
    subtitle2: "Start by defining a range you want to inspect from below.",
    input1: "Select the beginning date of the range",
    input2: "Select the ending date of the range",
    submit: "Continue",
    placeholder: "DD / MM / YYYY",
    back: "Go back",
    bearish: "Longest bearish trend",
    volume: "Highest trading volume",
    profit: "Most profitable range",
    from: "from",
    days: "days",
    in: "in",
    profitTip1: "In order to achieve the greatest possible revenue of ",
    profitTip2: " within given date range, you should have:",
    buy: "Bought",
    sell: "Sold",
    negative: "You shouldn't have bought Bitcoin during this date range as the profit would have been negative in any case.",
    noContent: "No specified dates to inspect. Please return back to home page to select the date range you want to look closer."
  },
  fi: {
    greeting: "Heippa! 👋",
    subtitle1_1: "Tarkastele ",
    subtitle1_2: "-tilastoja analysoidaksesi sen markkina-arvoa tietyllä aikavälillä.",
    subtitle2: "Aloita määrittelemällä alta aikaväli, jota haluat tutkia.",
    input1: "Valitse tutkittavan aikavälin aloituspäivämäärä",
    input2: "Valitse tutkittavan aikavälin lopetuspäivämäärä",
    submit: "Tarkastele",
    placeholder: "PV / KK / VVVV",
    back: "Takaisin",
    bearish: "Pisin laskeva trendi",
    volume: "Korkein kauppojen määrä",
    profit: "Tuottoisin aikaväli",
    from: "alkaen",
    days: "päivää",
    in: "päivämääränä",
    profitTip1: "Parhaan mahdollisen ",
    profitTip2: " tuoton saamiseksi annetulla aikavälillä, sinun olisi tullut:",
    buy: "Ostaa",
    sell: "Myydä",
    negative: "Sinun ei olisi kannattanut ostaa Bitcoinia tällä aikavälillä, sillä tuotto olisi ollut joka tapauksessa negatiivista.",
    noContent: "Tarkasteltavia päiviä ei ole määritelty. Ole hyvä ja palaa takaisin etusivulle valitsemaan aikaväli, jota halua tutkailla."
  }
}